include:
  - project: "the-microservice-dungeon/devops-team/common-ci-cd"
    ref: "0.2.0"
    file: "helm/package-publish.yaml"

stages:
  - build
  - helm

variables:
  PATH_TO_CHART: "helm-chart"
  CHART_NAME: "player-hackschnitzel"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - tag=latest
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${tag}" .
    - docker push "$CI_REGISTRY_IMAGE:${tag}"

helm-package-publish:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - ${PATH_TO_CHART}/**/*
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
